C++ compiler now requires C++11 support. Added basic font support via SDL_ttf (required package). Added rendering of button labels. Added HALT_ON_TRAP debug-flag for C6301::trap().

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -153,13 +153,24 @@ if [ ! -d "$BUILDROOT/release" ]; then mkdir $BUILDROOT/release; fi
 if [ ! -d "$BUILDROOT/work" ]; then mkdir $BUILDROOT/work; fi
 
 # ================================================
+# Detect C++11 support
+# ================================================
+
+$CXX -std=c++11 -dM -E -x c++ /dev/null 2>/dev/null >/dev/null
+if [ "$?" != "0" ]; then
+	echo "ERROR: ${CXX} doesn't support C++11!"
+	exit 1
+fi
+
+# ================================================
 # Find libraries
 # ================================================
 if [ "$KERNEL" == "SunOS" ]; then
+	# TODO: Add support for SDL_ttf
 	if [ "$PKG_SDL" == "" ]; then
-		pkg list developer/gcc-45 &>/dev/null
+		pkg list developer/gcc-48 &>/dev/null
 		if [ "$?" == "1" ]; then
-			echo "ERROR: Missing package developer/gcc-45"
+			echo "ERROR: Missing package developer/gcc-48"
 			exit 1
 		fi
 		
@@ -179,20 +190,21 @@ if [ "$KERNEL" == "SunOS" ]; then
 	fi
 elif [ "$KERNEL" == "Linux" ]; then
 	if [ "$TARGET" != "" ]; then
-		PKG_SDL="`${TARGET}-pkg-config --libs sdl 2>/dev/null`"
-		CXXFLAGS="$CXXFLAGS $(${TARGET}-pkg-config --cflags sdl)"
+		PKG_SDL="`${TARGET}-pkg-config --libs sdl SDL_ttf 2>/dev/null`"
+		CXXFLAGS="$CXXFLAGS $(${TARGET}-pkg-config --cflags sdl SDL_ttf)"
 	else
-		PKG_SDL="`pkg-config --libs sdl 2>/dev/null`"
-		CXXFLAGS="$CXXFLAGS $(pkg-config --cflags sdl)"
+		PKG_SDL="`pkg-config --libs sdl SDL_ttf 2>/dev/null`"
+		CXXFLAGS="$CXXFLAGS $(pkg-config --cflags sdl SDL_ttf)"
 	fi
 	
 	if [ "$PKG_SDL" == "" ]; then
-		echo "ERROR: Cannot find SDL!"
+		echo "ERROR: Cannot find SDL and/or SDL_ttf!"
 		exit 1
 	fi
 	
 	LDFLAGS="$LDFLAGS $PKG_SDL"
 elif [ "$KERNEL" == "Darwin" ]; then
+	# TODO: Add support for SDL_ttf
 	if [ "`xwhich sdl-config 2>/dev/null`" == "" ]; then
 		echo "ERROR: Cannot find SDL!"
 		exit 1
@@ -202,7 +214,7 @@ elif [ "$KERNEL" == "Darwin" ]; then
 	CXXFLAGS="$CXXFLAGS $(sdl-config --cflags)"
 else
 	if [ "$PKG_SDL" == "" ]; then
-		echo "ERROR: Unhandled auto-detection for SDL on $KERNEL! Please set PKG_SDL=1 and set LDFLAGS/CXXFLAGS manually. Sorry :("
+		echo "ERROR: Unhandled auto-detection for SDL and SDL_ttf on $KERNEL! Please set PKG_SDL=1 and set LDFLAGS/CXXFLAGS manually. Sorry :("
 		exit 1
 	fi
 fi
